version: '3.1'

services:
#  golang-service:
#    container_name: movie-go-container
#    image: movie_img
#    ports:
#      - 3000:3000

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgresql

  adminer:
    image: adminer
    ports:
      - 8080:8080


